const CACHE='forced-self-care-v22';
const ASSETS=['./','index.html','manifest.webmanifest','icon.png','heart-message.gif'];
self.addEventListener('message',event=>{if(event.data?.type==='SET_ROLE')event.waitUntil(setMeta('role',event.data.role));if(event.data?.type==='CLEAR_BADGE')event.waitUntil(Promise.all([setMeta('badgeCount',0),'clearAppBadge' in self.navigator?self.navigator.clearAppBadge():Promise.resolve()]))});
const badgeDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('forced-self-care-badges',1);request.onupgradeneeded=()=>request.result.createObjectStore('meta');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
const getMeta=async key=>{const db=await badgeDb();return new Promise((resolve,reject)=>{const request=db.transaction('meta').objectStore('meta').get(key);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})};
const setMeta=async(key,value)=>{const db=await badgeDb();return new Promise((resolve,reject)=>{const request=db.transaction('meta','readwrite').objectStore('meta').put(value,key);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})};
async function addMonitorBadge(){try{if(await getMeta('role')!=='monitor'||!('setAppBadge' in self.navigator))return;const count=Number(await getMeta('badgeCount')||0)+1;await setMeta('badgeCount',count);await self.navigator.setAppBadge(count)}catch{}}
self.addEventListener('install',event=>event.waitUntil(Promise.all([caches.open(CACHE).then(cache=>cache.addAll(ASSETS)),self.skipWaiting()])));
self.addEventListener('activate',event=>event.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))),self.clients.claim()])));
const decorateAppHtml=html=>html
  .replace('</style>','.message-heart-gif{height:48px;width:100%;display:flex;justify-content:center;align-items:center;margin:0 0 8px;overflow:visible}.message-heart-gif img{width:48px;height:48px;display:block;object-fit:contain}</style>')
  .replace(/function addCupidAnimation\(\)\{.*?\n    async function syncAppBadge/s,"function addCupidAnimation(){const heart=document.querySelector('.love-quote .heart');if(!heart)return;heart.className='message-heart-gif';heart.setAttribute('aria-label','Animated puzzle heart');heart.innerHTML='<img src=\"heart-message.gif\" alt=\"\" aria-hidden=\"true\">'}\n    async function syncAppBadge");
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;const url=new URL(event.request.url);if(event.request.mode==='navigate'||url.pathname.endsWith('/index.html')||url.pathname==='/'){event.respondWith(fetch(event.request).then(async response=>{if(!response.ok)return response;const headers=new Headers(response.headers);headers.set('content-type','text/html; charset=utf-8');return new Response(decorateAppHtml(await response.text()),{status:response.status,statusText:response.statusText,headers})}).catch(()=>caches.match('index.html').then(async response=>response?new Response(decorateAppHtml(await response.text()),{headers:{'content-type':'text/html; charset=utf-8'}}):response)));return}event.respondWith(fetch(event.request).catch(()=>caches.match(event.request)))});
self.addEventListener('push',event=>{let data={title:'Forced Self Care',body:'Medication reminder',tag:'reminder',url:'./'};try{data={...data,...event.data.json()}}catch{}event.waitUntil(Promise.all([self.registration.showNotification(data.title,{body:data.body,icon:'icon.png',badge:'icon.png',tag:data.tag,data:{url:data.url},vibrate:[300,150,300],requireInteraction:true}),addMonitorBadge()]))});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(list=>{for(const client of list){if('focus' in client)return client.focus()}return clients.openWindow(event.notification.data?.url||'./')}))});
